name: IntegrationTest

on:
  workflow_run:
    workflows: ["maven-build"]
    types:
      - completed

permissions:
  actions: read  
  contents: read

jobs:
  test-services:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Download Artifact from Build Workflow
        uses: actions/download-artifact@v4
        with:
          name: clinicare-artifact
          path: integrationjavafx4/pidevjavaFx/roar
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare JAR for Docker
        working-directory: ./integrationjavafx4/pidevjavaFx/roar
        run: |
          echo "Posiziono il JAR scaricato..."
          find . -name "CliniCare.jar" -exec mv {} . \;
          ls -la CliniCare.jar

      - name: Start Services and Test
        working-directory: ./integrationjavafx4/pidevjavaFx/roar
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          DB_NAME: clinicare_db
        run: |
          docker compose up -d --build
          
          echo "Attendo 20 secondi per l'avvio..."
          sleep 20
          
          docker compose ps
          docker compose logs app
          
      - name: Stop Services
        if: always()
        working-directory: ./integrationjavafx4/pidevjavaFx/roar
        run: docker compose down
