name: maven-build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Download OpenJML
      run: wget https://github.com/OpenJML/OpenJML/releases/download/0.8.51-alpha/openjml.jar -O openjml.jar

    - name: Prepare JML Environment
      working-directory: ./integrationjavafx4/pidevjavaFx/roar
      run: |
        mvn compile -DskipTests
        mvn dependency:build-classpath -Dmdep.outputFile=cp.txt

    - name: Run JML Verification
      working-directory: ./integrationjavafx4/pidevjavaFx/roar
      run: |
        export PROJ_CP=$(cat cp.txt)
        OPENJML_PATH="../../../openjml.jar"
        TARGET_DIRS="src/main/java/entite src/main/java/service src/main/java/util"
        
        echo "Eseguendo JML Check..."
        java -jar $OPENJML_PATH -esc -cp "$PROJ_CP:target/classes" --dirs $TARGET_DIRS

    - name: Build package
      working-directory: ./integrationjavafx4/pidevjavaFx/roar
      run: mvn -B package

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: success() 
      with:
        name: clinicare-artifact
        path: integrationjavafx4/pidevjavaFx/roar/target/CliniCare.jar

  docker-push:
    needs: build  
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: clinicare-artifact
          path: integrationjavafx4/pidevjavaFx/roar

      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355
        with:
          context: integrationjavafx4/pidevjavaFx/roar
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/clinicare:latest
